const fs = require('fs');
const file = 'd:/service-marketplace/user-dashboard/src/pages/Services.jsx';
let content = fs.readFileSync(file, 'utf8').split('\n');
content.splice(852, 11,
  '              {location && (',
  '                <div className="location-map-container" style={{ border: "none", boxShadow: "0 4px 12px rgba(0,0,0,0.08)", borderRadius: "16px", overflow: "hidden" }}>',
  '                  <iframe',
  '                    title="Your current location"',
  '                    className="location-map-modal"',
  '                    src={mapUrl}',
  '                    loading="lazy"',
  '                    style={{ borderBottom: "1px solid #E2E8F0", height: "280px", width: "100%", border: "none" }}',
  '                  />',
  '                  <div style={{ padding: "16px", background: "#fff", display: "flex", flexDirection: "column", gap: "14px" }}>',
  '                    <p style={{ margin: 0, fontSize: "13px", color: "#475569", lineHeight: "1.5" }}>',
  '                      <MapPin size={16} color="#2563eb" style={{ display: "inline", marginRight: "6px", verticalAlign: "text-bottom" }} />',
  '                      <strong style={{ color: "#1E293B" }}>{location.placeName || locationName}</strong> is set as your service location.',
  '                    </p>',
  '                    <button',
  '                      onClick={() => setShowLocationModal(false)}',
  '                      style={{',
  '                        background: "#2563eb",',
  '                        color: "white",',
  '                        border: "none",',
  '                        padding: "14px",',
  '                        borderRadius: "12px",',
  '                        fontWeight: "700",',
  '                        cursor: "pointer",',
  '                        fontSize: "15px",',
  '                        width: "100%",',
  '                        transition: "background 0.2s",',
  '                        boxShadow: "0 2px 8px rgba(37, 99, 235, 0.25)"',
  '                      }}',
  '                    >',
  '                      Looks Good, Continue',
  '                    </button>',
  '                  </div>',
  '                </div>',
  '              )}'
);
fs.writeFileSync(file, content.join('\n'));
